version: '3'
services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '4000:3000'
    volumes:
      - .:/opt/app  
    links:
      - mongo  
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27019:27017'