version: '3'

services: 

  web:
    build: # build from custom Dockerfile.dev
      context: . # path from where to create / to Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # do not try to map a folder node_modules inside the container
      - .:/app # map current dir ( my app - frontend ) to dir inside the container

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules  
      - .:/app
    command: ["npm", "run", "test"]












 # i5!S@TnWkWeyT3P   